rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3

gemfile:
  - test/gemfiles/Gemfile.rails-3.0.x
  - test/gemfiles/Gemfile.rails-3.1.x
  - test/gemfiles/Gemfile.rails-3.2.x
  - test/gemfiles/Gemfile.rails-edge

matrix:
  exclude:
    - rvm: 1.8.7
      gemfile: test/gemfiles/Gemfile.rails-edge
    - rvm: 1.9.2
      gemfile: test/gemfiles/Gemfile.rails-edge

notifications:
  email: false
